// Auto-generated by scripts/generate_param_compat.go
// DO NOT EDIT MANUALLY

#pragma once
#include <map>
#include <string>

namespace mihomo {

struct ParamCompatInfo {
    bool supported;
    std::string type;
};

const std::map<std::string, std::map<std::string, ParamCompatInfo>> PARAM_COMPAT = {
    // Protocol: anytls
    {"anytls", {
        {"alpn", {true, "array"}}, // anytls
        {"certificate", {true, "string"}}, // anytls
        {"client-fingerprint", {true, "string"}}, // anytls
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"ech-opts", {true, "string"}}, // anytls
        {"fingerprint", {true, "string"}}, // anytls
        {"idle-session-check-interval", {true, "int"}}, // anytls
        {"idle-session-timeout", {true, "int"}}, // anytls
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"min-idle-session", {true, "int"}}, // anytls
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // anytls
        {"password", {true, "string"}}, // anytls
        {"port", {true, "int"}}, // anytls
        {"private-key", {true, "string"}}, // anytls
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // anytls
        {"skip-cert-verify", {true, "bool"}}, // anytls
        {"sni", {true, "string"}}, // anytls
        {"tfo", {true, "bool"}}, // BasicOption
        {"udp", {true, "bool"}}, // anytls
    }},
    // Protocol: http
    {"http", {
        {"certificate", {true, "string"}}, // http
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"fingerprint", {true, "string"}}, // http
        {"headers", {true, "object"}}, // http
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // http
        {"password", {true, "string"}}, // http
        {"port", {true, "int"}}, // http
        {"private-key", {true, "string"}}, // http
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // http
        {"skip-cert-verify", {true, "bool"}}, // http
        {"sni", {true, "string"}}, // http
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // http
        {"username", {true, "string"}}, // http
    }},
    // Protocol: https
    {"https", {
        {"certificate", {true, "string"}}, // https
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"fingerprint", {true, "string"}}, // https
        {"headers", {true, "object"}}, // https
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // https
        {"password", {true, "string"}}, // https
        {"port", {true, "int"}}, // https
        {"private-key", {true, "string"}}, // https
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // https
        {"skip-cert-verify", {true, "bool"}}, // https
        {"sni", {true, "string"}}, // https
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // https
        {"username", {true, "string"}}, // https
    }},
    // Protocol: hy2
    {"hy2", {
        {"alpn", {true, "array"}}, // hy2
        {"certificate", {true, "string"}}, // hy2
        {"cwnd", {true, "int"}}, // hy2
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"down", {true, "string"}}, // hy2
        {"ech-opts", {true, "string"}}, // hy2
        {"fingerprint", {true, "string"}}, // hy2
        {"hop-interval", {true, "int"}}, // hy2
        {"initial-connection-receive-window", {true, "int"}}, // hy2
        {"initial-stream-receive-window", {true, "int"}}, // hy2
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"max-connection-receive-window", {true, "int"}}, // hy2
        {"max-stream-receive-window", {true, "int"}}, // hy2
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // hy2
        {"obfs", {true, "string"}}, // hy2
        {"obfs-password", {true, "string"}}, // hy2
        {"password", {true, "string"}}, // hy2
        {"port", {true, "int"}}, // hy2
        {"ports", {true, "string"}}, // hy2
        {"private-key", {true, "string"}}, // hy2
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // hy2
        {"skip-cert-verify", {true, "bool"}}, // hy2
        {"sni", {true, "string"}}, // hy2
        {"tfo", {true, "bool"}}, // BasicOption
        {"udp-mtu", {true, "int"}}, // hy2
        {"up", {true, "string"}}, // hy2
    }},
    // Protocol: hysteria
    {"hysteria", {
        {"alpn", {true, "array"}}, // hysteria
        {"auth", {true, "string"}}, // hysteria
        {"auth-str", {true, "string"}}, // hysteria
        {"certificate", {true, "string"}}, // hysteria
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"disable-mtu-discovery", {true, "bool"}}, // hysteria
        {"down", {true, "string"}}, // hysteria
        {"down-speed", {true, "int"}}, // hysteria
        {"ech-opts", {true, "string"}}, // hysteria
        {"fast-open", {true, "bool"}}, // hysteria
        {"fingerprint", {true, "string"}}, // hysteria
        {"hop-interval", {true, "int"}}, // hysteria
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // hysteria
        {"obfs", {true, "string"}}, // hysteria
        {"obfs-protocol", {true, "string"}}, // hysteria
        {"port", {true, "int"}}, // hysteria
        {"ports", {true, "string"}}, // hysteria
        {"private-key", {true, "string"}}, // hysteria
        {"protocol", {true, "string"}}, // hysteria
        {"recv-window", {true, "int"}}, // hysteria
        {"recv-window-conn", {true, "int"}}, // hysteria
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // hysteria
        {"skip-cert-verify", {true, "bool"}}, // hysteria
        {"sni", {true, "string"}}, // hysteria
        {"tfo", {true, "bool"}}, // BasicOption
        {"up", {true, "string"}}, // hysteria
        {"up-speed", {true, "int"}}, // hysteria
    }},
    // Protocol: hysteria2
    {"hysteria2", {
        {"alpn", {true, "array"}}, // hysteria2
        {"certificate", {true, "string"}}, // hysteria2
        {"cwnd", {true, "int"}}, // hysteria2
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"down", {true, "string"}}, // hysteria2
        {"ech-opts", {true, "string"}}, // hysteria2
        {"fingerprint", {true, "string"}}, // hysteria2
        {"hop-interval", {true, "int"}}, // hysteria2
        {"initial-connection-receive-window", {true, "int"}}, // hysteria2
        {"initial-stream-receive-window", {true, "int"}}, // hysteria2
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"max-connection-receive-window", {true, "int"}}, // hysteria2
        {"max-stream-receive-window", {true, "int"}}, // hysteria2
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // hysteria2
        {"obfs", {true, "string"}}, // hysteria2
        {"obfs-password", {true, "string"}}, // hysteria2
        {"password", {true, "string"}}, // hysteria2
        {"port", {true, "int"}}, // hysteria2
        {"ports", {true, "string"}}, // hysteria2
        {"private-key", {true, "string"}}, // hysteria2
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // hysteria2
        {"skip-cert-verify", {true, "bool"}}, // hysteria2
        {"sni", {true, "string"}}, // hysteria2
        {"tfo", {true, "bool"}}, // BasicOption
        {"udp-mtu", {true, "int"}}, // hysteria2
        {"up", {true, "string"}}, // hysteria2
    }},
    // Protocol: socks
    {"socks", {
        {"certificate", {true, "string"}}, // socks
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"fingerprint", {true, "string"}}, // socks
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // socks
        {"password", {true, "string"}}, // socks
        {"port", {true, "int"}}, // socks
        {"private-key", {true, "string"}}, // socks
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // socks
        {"skip-cert-verify", {true, "bool"}}, // socks
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // socks
        {"udp", {true, "bool"}}, // socks
        {"username", {true, "string"}}, // socks
    }},
    // Protocol: socks5
    {"socks5", {
        {"certificate", {true, "string"}}, // socks5
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"fingerprint", {true, "string"}}, // socks5
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // socks5
        {"password", {true, "string"}}, // socks5
        {"port", {true, "int"}}, // socks5
        {"private-key", {true, "string"}}, // socks5
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // socks5
        {"skip-cert-verify", {true, "bool"}}, // socks5
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // socks5
        {"udp", {true, "bool"}}, // socks5
        {"username", {true, "string"}}, // socks5
    }},
    // Protocol: socks5h
    {"socks5h", {
        {"certificate", {true, "string"}}, // socks5h
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"fingerprint", {true, "string"}}, // socks5h
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // socks5h
        {"password", {true, "string"}}, // socks5h
        {"port", {true, "int"}}, // socks5h
        {"private-key", {true, "string"}}, // socks5h
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // socks5h
        {"skip-cert-verify", {true, "bool"}}, // socks5h
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // socks5h
        {"udp", {true, "bool"}}, // socks5h
        {"username", {true, "string"}}, // socks5h
    }},
    // Protocol: ss
    {"ss", {
        {"cipher", {true, "string"}}, // ss
        {"client-fingerprint", {true, "string"}}, // ss
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // ss
        {"password", {true, "string"}}, // ss
        {"plugin", {true, "string"}}, // ss
        {"plugin-opts", {true, "object"}}, // ss
        {"port", {true, "int"}}, // ss
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // ss
        {"tfo", {true, "bool"}}, // BasicOption
        {"udp", {true, "bool"}}, // ss
        {"udp-over-tcp", {true, "bool"}}, // ss
        {"udp-over-tcp-version", {true, "int"}}, // ss
    }},
    // Protocol: ssr
    {"ssr", {
        {"cipher", {true, "string"}}, // ssr
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // ssr
        {"obfs", {true, "string"}}, // ssr
        {"obfs-param", {true, "string"}}, // ssr
        {"password", {true, "string"}}, // ssr
        {"port", {true, "int"}}, // ssr
        {"protocol", {true, "string"}}, // ssr
        {"protocol-param", {true, "string"}}, // ssr
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // ssr
        {"tfo", {true, "bool"}}, // BasicOption
        {"udp", {true, "bool"}}, // ssr
    }},
    // Protocol: trojan
    {"trojan", {
        {"alpn", {true, "array"}}, // trojan
        {"certificate", {true, "string"}}, // trojan
        {"client-fingerprint", {true, "string"}}, // trojan
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"ech-opts", {true, "string"}}, // trojan
        {"fingerprint", {true, "string"}}, // trojan
        {"grpc-opts", {true, "string"}}, // trojan
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // trojan
        {"network", {true, "string"}}, // trojan
        {"password", {true, "string"}}, // trojan
        {"port", {true, "int"}}, // trojan
        {"private-key", {true, "string"}}, // trojan
        {"reality-opts", {true, "string"}}, // trojan
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // trojan
        {"skip-cert-verify", {true, "bool"}}, // trojan
        {"sni", {true, "string"}}, // trojan
        {"ss-opts", {true, "string"}}, // trojan
        {"tfo", {true, "bool"}}, // BasicOption
        {"udp", {true, "bool"}}, // trojan
        {"ws-opts", {true, "string"}}, // trojan
    }},
    // Protocol: tuic
    {"tuic", {
        {"alpn", {true, "array"}}, // tuic
        {"certificate", {true, "string"}}, // tuic
        {"congestion-controller", {true, "string"}}, // tuic
        {"cwnd", {true, "int"}}, // tuic
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"disable-mtu-discovery", {true, "bool"}}, // tuic
        {"disable-sni", {true, "bool"}}, // tuic
        {"ech-opts", {true, "string"}}, // tuic
        {"fast-open", {true, "bool"}}, // tuic
        {"fingerprint", {true, "string"}}, // tuic
        {"heartbeat-interval", {true, "int"}}, // tuic
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip", {true, "string"}}, // tuic
        {"ip-version", {true, "string"}}, // BasicOption
        {"max-datagram-frame-size", {true, "int"}}, // tuic
        {"max-open-streams", {true, "int"}}, // tuic
        {"max-udp-relay-packet-size", {true, "int"}}, // tuic
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // tuic
        {"password", {true, "string"}}, // tuic
        {"port", {true, "int"}}, // tuic
        {"private-key", {true, "string"}}, // tuic
        {"recv-window", {true, "int"}}, // tuic
        {"recv-window-conn", {true, "int"}}, // tuic
        {"reduce-rtt", {true, "bool"}}, // tuic
        {"request-timeout", {true, "int"}}, // tuic
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // tuic
        {"skip-cert-verify", {true, "bool"}}, // tuic
        {"sni", {true, "string"}}, // tuic
        {"tfo", {true, "bool"}}, // BasicOption
        {"token", {true, "string"}}, // tuic
        {"udp-over-stream", {true, "bool"}}, // tuic
        {"udp-over-stream-version", {true, "int"}}, // tuic
        {"udp-relay-mode", {true, "string"}}, // tuic
        {"uuid", {true, "string"}}, // tuic
    }},
    // Protocol: vless
    {"vless", {
        {"alpn", {true, "array"}}, // vless
        {"certificate", {true, "string"}}, // vless
        {"client-fingerprint", {true, "string"}}, // vless
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"ech-opts", {true, "string"}}, // vless
        {"encryption", {true, "string"}}, // vless
        {"fingerprint", {true, "string"}}, // vless
        {"flow", {true, "string"}}, // vless
        {"grpc-opts", {true, "string"}}, // vless
        {"h2-opts", {true, "string"}}, // vless
        {"http-opts", {true, "string"}}, // vless
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // vless
        {"network", {true, "string"}}, // vless
        {"packet-addr", {true, "bool"}}, // vless
        {"packet-encoding", {true, "string"}}, // vless
        {"port", {true, "int"}}, // vless
        {"private-key", {true, "string"}}, // vless
        {"reality-opts", {true, "string"}}, // vless
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // vless
        {"servername", {true, "string"}}, // vless
        {"skip-cert-verify", {true, "bool"}}, // vless
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // vless
        {"udp", {true, "bool"}}, // vless
        {"uuid", {true, "string"}}, // vless
        {"ws-headers", {true, "object"}}, // vless
        {"ws-opts", {true, "string"}}, // vless
        {"xudp", {true, "bool"}}, // vless
    }},
    // Protocol: vmess
    {"vmess", {
        {"alpn", {true, "array"}}, // vmess
        {"alterId", {true, "int"}}, // vmess
        {"authenticated-length", {true, "bool"}}, // vmess
        {"certificate", {true, "string"}}, // vmess
        {"cipher", {true, "string"}}, // vmess
        {"client-fingerprint", {true, "string"}}, // vmess
        {"dialer-proxy", {true, "string"}}, // BasicOption
        {"ech-opts", {true, "string"}}, // vmess
        {"fingerprint", {true, "string"}}, // vmess
        {"global-padding", {true, "bool"}}, // vmess
        {"grpc-opts", {true, "string"}}, // vmess
        {"h2-opts", {true, "string"}}, // vmess
        {"http-opts", {true, "string"}}, // vmess
        {"interface-name", {true, "string"}}, // BasicOption
        {"ip-version", {true, "string"}}, // BasicOption
        {"mptcp", {true, "bool"}}, // BasicOption
        {"name", {true, "string"}}, // vmess
        {"network", {true, "string"}}, // vmess
        {"packet-addr", {true, "bool"}}, // vmess
        {"packet-encoding", {true, "string"}}, // vmess
        {"port", {true, "int"}}, // vmess
        {"private-key", {true, "string"}}, // vmess
        {"reality-opts", {true, "string"}}, // vmess
        {"routing-mark", {true, "int"}}, // BasicOption
        {"server", {true, "string"}}, // vmess
        {"servername", {true, "string"}}, // vmess
        {"skip-cert-verify", {true, "bool"}}, // vmess
        {"tfo", {true, "bool"}}, // BasicOption
        {"tls", {true, "bool"}}, // vmess
        {"udp", {true, "bool"}}, // vmess
        {"uuid", {true, "string"}}, // vmess
        {"ws-opts", {true, "string"}}, // vmess
        {"xudp", {true, "bool"}}, // vmess
    }},
};

// Check if a protocol supports a specific parameter
inline bool isParamSupported(const std::string& protocol, const std::string& param) {
    auto proto_it = PARAM_COMPAT.find(protocol);
    if (proto_it == PARAM_COMPAT.end()) return false;
    auto param_it = proto_it->second.find(param);
    return param_it != proto_it->second.end() && param_it->second.supported;
}

} // namespace mihomo
